# -*- coding: utf-8 -*-
"""MiniProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1165kwUoUEHM84fdJ6aQgk5dR1M7D32jy
"""

from google.colab import files
uploaded = files.upload()
print(uploaded)

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
from matplotlib import pyplot as plt
# %matplotlib inline

df = pd.read_csv("DUQ_hourly.csv.zip")
df

df.head()

df.info()
df.describe()

df.isnull().sum()

df = df.drop_duplicates()

df = df.sort_index()

df_sample = df.head(1000)

plt.figure(figsize=(10,5))
plt.plot(df_sample['Datetime'], df_sample['DUQ_MW'])
plt.show()

print(df.columns)

df = df.reset_index().drop('Datetime', axis=1)

df = pd.read_csv("DUQ_hourly.csv.zip", parse_dates=['Datetime'])
df.set_index('Datetime', inplace=True)

print(df.columns)

X = df.drop('DUQ_MW', axis=1)

print(X.dtypes)

print(X.columns)

df.index = pd.to_datetime(df.index)
df.reset_index().set_index('Datetime', inplace=True)
df['hour'] = df.index.hour
df['day_of_week'] = df.index.dayofweek
df['month'] = df.index.month
df['lag_1'] = df['DUQ_MW'].shift(1)
X = df.drop('DUQ_MW', axis=1)
y = df['DUQ_MW']

train_size = int(len(df) * 0.8)

X_train = X[:train_size]
X_test = X[train_size:]

y_train = y[:train_size]
y_test = y[train_size:]

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100)
model.fit(X_train, y_train)

preds = model.predict(X_test)

feature_columns = X.columns

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, preds)
print("MAE:", mae)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
plt.plot(y_test.index[:200], y_test[:200], label="Actual")
plt.plot(y_test.index[:200], preds[:200], label="Predicted")
plt.legend()
plt.show()

user_input = input("Enter date and time (DD-MM-YYYY HH:MM): ")
user_datetime = pd.to_datetime(user_input, dayfirst=True)
last_actual_value = df.iloc[-1]['DUQ_MW']
first_row = pd.DataFrame({
    'hour': [user_datetime.hour],
    'day_of_week': [user_datetime.dayofweek],
    'month': [user_datetime.month],
    'lag_1': [last_actual_value]
})
current_prediction = model.predict(first_row[X.columns])[0]

print(f"\n🚀 Prediction for {user_datetime}: {current_prediction:.2f} MW")
print("-" * 40)
choice = input("Do you want to see the forecast for the next 24 hours? (yes/no): ").lower()

if choice == 'yes':
    forecast_results = []
    last_val = current_prediction
    loop_time = user_datetime

    for i in range(24):
        loop_time += pd.Timedelta(hours=1)

        row = pd.DataFrame({
            'hour': [loop_time.hour],
            'day_of_week': [loop_time.dayofweek],
            'month': [loop_time.month],
            'lag_1': [last_val]
        })
        pred = model.predict(row[X.columns])[0]
        forecast_results.append({'Time': loop_time, 'Predicted_MW': pred})
        last_val = pred
    forecast_df = pd.DataFrame(forecast_results)
    print("\n📅 24-Hour Forecast:")
    print(forecast_df)
else:
    print("24-hour forecast skipped.")